# Generated by Django 3.2.3 on 2021-06-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Decks',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('architect', models.BooleanField(default=False)),
                ('finished_decks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.deck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(default='Tytuł X', max_length=100)),
                ('points', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='card_image')),
                ('accept_choice_info', models.CharField(default='Tak', max_length=255)),
                ('reject_choice_info', models.CharField(default='Nie', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('INFO', 'Informational'), ('ACT', 'Action')], default='INFO', max_length=10)),
                ('accept_choice', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accept_choices', to='feed.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.deck')),
                ('reject_choice', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_chocices', to='feed.card')),
            ],
        ),
    ]
