# Generated by Django 3.2.3 on 2021-06-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Decks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('points', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='card_image')),
                ('state', models.BooleanField(default=False)),
                ('card_type', models.CharField(choices=[('INFO', 'Informational'), ('ACT', 'Action')], default='INFO', max_length=10)),
                ('accept_choice', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accept_choices', to='feed.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.deck')),
                ('reject_chocice', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_chocices', to='feed.card')),
            ],
        ),
    ]
