# Generated by Django 3.2.3 on 2021-06-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='state',
            new_name='is_active',
        ),
    ]
