# Generated by Django 3.2.3 on 2021-06-13 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20210613_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='reject_chocice',
            new_name='reject_choice',
        ),
        migrations.AddField(
            model_name='card',
            name='accept_choice_info',
            field=models.CharField(default='Tak', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='reject_choice_info',
            field=models.CharField(default='Nie', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='Tytuł X', max_length=100),
        ),
    ]
