# Generated by Django 3.2.3 on 2021-06-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_player_finished_decks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='reject_choice_info',
            field=models.CharField(blank=True, default='Nie', max_length=255),
        ),
    ]
