# Generated by Django 3.2.3 on 2021-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
